# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_meetup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptype',
            name='slug',
            field=models.SlugField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together=set([('number', 'meetup_type')]),
        ),
    ]
