language: python
cache: pip
python:
  - "3.7"
before_install:
  - export DJANGO_SETTINGS_MODULE="meetpy.settings.ci"
install:
  - pipenv install
  - pipenv install --dev
before_script:
  - cd meetpy
  - pipenv run ./manage.py migrate
script:
  - pipenv run pytest
